# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on: [ push, pull_request ]

jobs:
    compatibility-test-node:
        name: Test Node Version Compatibility
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [ 10.x, 12.x ]

        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
              node-version: ${{ matrix.node-version }}
        - run: npm ci
        - run: npm install release-it
        - run: npm run build --if-present
        - run: npm run test

    compatibility-test-release:
        name: Test Release-it Version Compatibility
        runs-on: ubuntu-latest

        strategy:
            matrix:
                release-it-version: [ 11.x, 12.x, 13.x, 14.x ]

        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
              node-version: 14.x
        - run: npm ci
        - run: npm install release-it@${{ matrix.release-it-version }}
        - run: npm run build --if-present
        - run: npm run test

    coverage:
        name: Coverage
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
              node-version: 14.x
        - run: npm ci
        - run: npm install release-it
        - run: npm run build --if-present
        - run: npm run test+coverage
        - run: npx c8 report --reporter lcov
        - name: Upload coverage to Codacy
          # Change back to
          # uses: codacy/codacy-coverage-reporter-action@master
          # when https://github.com/codacy/codacy-coverage-reporter-action/issues/36 is fixed
          uses: codacy/codacy-coverage-reporter-action@5409fccf86ceb72547bb9fe6673ea2d3b4f62e6f
          with:
              project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
              coverage-reports: coverage/lcov.info
